<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractPostsEvents
{
    /**
     * The mupostsmodule.content_post_load event is thrown when contents
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const CONTENT_POST_LOAD = 'mupostsmodule.content_post_load';
    
    /**
     * The mupostsmodule.content_pre_persist event is thrown before a new content
     * is created in the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const CONTENT_PRE_PERSIST = 'mupostsmodule.content_pre_persist';
    
    /**
     * The mupostsmodule.content_post_persist event is thrown after a new content
     * has been created in the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const CONTENT_POST_PERSIST = 'mupostsmodule.content_post_persist';
    
    /**
     * The mupostsmodule.content_pre_remove event is thrown before an existing content
     * is removed from the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const CONTENT_PRE_REMOVE = 'mupostsmodule.content_pre_remove';
    
    /**
     * The mupostsmodule.content_post_remove event is thrown after an existing content
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const CONTENT_POST_REMOVE = 'mupostsmodule.content_post_remove';
    
    /**
     * The mupostsmodule.content_pre_update event is thrown before an existing content
     * is updated in the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const CONTENT_PRE_UPDATE = 'mupostsmodule.content_pre_update';
    
    /**
     * The mupostsmodule.content_post_update event is thrown after an existing new content
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\PostsModule\Event\FilterContentEvent instance.
     *
     * @see MU\PostsModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const CONTENT_POST_UPDATE = 'mupostsmodule.content_post_update';
    
}
