<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Form\Type\QuickNavigation;

use MU\PostsModule\Form\Type\QuickNavigation\Base\AbstractContentQuickNavType;

/**
 * Content quick navigation form type implementation class.
 */
class ContentQuickNavType extends AbstractContentQuickNavType
{
    // feel free to extend the base form type class here
}
