<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\DependencyInjection;

use MU\PostsModule\DependencyInjection\Base\AbstractMUPostsExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUPostsExtension extends AbstractMUPostsExtension
{
    // custom enhancements can go here
}
