<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Entity\Factory\Base;

use MU\PostsModule\Entity\ContentEntity;
use MU\PostsModule\Helper\ListEntriesHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var ListEntriesHelper Helper service for managing list entries
     */
    protected $listEntriesHelper;

    /**
     * EntityInitialiser constructor.
     *
     * @param ListEntriesHelper $listEntriesHelper Helper service for managing list entries
     */
    public function __construct(ListEntriesHelper $listEntriesHelper)
    {
        $this->listEntriesHelper = $listEntriesHelper;
    }

    /**
     * Initialises a given content instance.
     *
     * @param ContentEntity $entity The newly created entity instance
     *
     * @return ContentEntity The updated entity instance
     */
    public function initContent(ContentEntity $entity)
    {
        $listEntries = $this->listEntriesHelper->getEntries('content', 'experienceOfNature');
        foreach ($listEntries as $listEntry) {
            if (true === $listEntry['default']) {
                $entity->setExperienceOfNature($listEntry['value']);
                break;
            }
        }

        $listEntries = $this->listEntriesHelper->getEntries('content', 'levelOfDifficulty');
        foreach ($listEntries as $listEntry) {
            if (true === $listEntry['default']) {
                $entity->setLevelOfDifficulty($listEntry['value']);
                break;
            }
        }

        $listEntries = $this->listEntriesHelper->getEntries('content', 'requiredFitness');
        foreach ($listEntries as $listEntry) {
            if (true === $listEntry['default']) {
                $entity->setRequiredFitness($listEntry['value']);
                break;
            }
        }

        $listEntries = $this->listEntriesHelper->getEntries('content', 'other');
        $items = [];
        foreach ($listEntries as $listEntry) {
            if (true === $listEntry['default']) {
                $items[] = $listEntry['value'];
            }
        }
        $entity->setOther(implode('###', $items));


        return $entity;
    }

    /**
     * Returns the list entries helper.
     *
     * @return ListEntriesHelper
     */
    public function getListEntriesHelper()
    {
        return $this->listEntriesHelper;
    }
    
    /**
     * Sets the list entries helper.
     *
     * @param ListEntriesHelper $listEntriesHelper
     *
     * @return void
     */
    public function setListEntriesHelper($listEntriesHelper)
    {
        if ($this->listEntriesHelper != $listEntriesHelper) {
            $this->listEntriesHelper = $listEntriesHelper;
        }
    }
    
}
