<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Event;

use MU\PostsModule\Event\Base\AbstractFilterContentEvent;

/**
 * Event implementation class for filtering content processing.
 */
class FilterContentEvent extends AbstractFilterContentEvent
{
    // feel free to extend the event class here
}
