<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Form\Type;

use MU\PostsModule\Form\Type\Base\AbstractContentType;

/**
 * Content editing form type implementation class.
 */
class ContentType extends AbstractContentType
{
    // feel free to extend the content editing form type class here
}
