<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Form\Handler\Content;

use MU\PostsModule\Form\Handler\Content\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the content object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
