<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Entity;

use MU\PostsModule\Entity\Base\AbstractContentEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for content entities.
 * @ORM\Entity(repositoryClass="MU\PostsModule\Entity\Repository\ContentRepository")
 * @ORM\Table(name="mu_posts_content",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 * @UniqueEntity(fields="slug", ignoreNull="false")
 */
class ContentEntity extends BaseEntity
{
    // feel free to add your own methods here
}
