services:
    mu_posts_module.app_settings:
        class: MU\PostsModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
