services:
    # Helper services
    mu_posts_module.archive_helper:
        class: MU\PostsModule\Helper\ArchiveHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@mu_posts_module.entity_factory"
            - "@mu_posts_module.workflow_helper"
            - "@mu_posts_module.hook_helper"
    
    mu_posts_module.category_helper:
        class: MU\PostsModule\Helper\CategoryHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_categories_module.category_registry_repository"
            - "@zikula_categories_module.api.category_permission"
    
    mu_posts_module.collection_filter_helper:
        class: MU\PostsModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_users_module.current_user"
            - "@mu_posts_module.category_helper"
            - "@=service('zikula_extensions_module.api.variable').get('MUPostsModule', 'showOnlyOwnEntries', false)"
    
    mu_posts_module.controller_helper:
        class: MU\PostsModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_posts_module.archive_helper"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_posts_module.entity_factory"
            - "@mu_posts_module.collection_filter_helper"
            - "@mu_posts_module.model_helper"
            - "@mu_posts_module.feature_activation_helper"
    
    mu_posts_module.entity_display_helper:
        class: MU\PostsModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_posts_module.listentries_helper"
    
    mu_posts_module.feature_activation_helper:
        class: MU\PostsModule\Helper\FeatureActivationHelper
    
    mu_posts_module.hook_helper:
        class: MU\PostsModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    mu_posts_module.listentries_helper:
        class: MU\PostsModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    mu_posts_module.model_helper:
        class: MU\PostsModule\Helper\ModelHelper
        arguments:
            - "@mu_posts_module.entity_factory"
    
    mu_posts_module.notification_helper:
        class: MU\PostsModule\Helper\NotificationHelper
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@session"
            - "@router"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@twig"
            - "@zikula_mailer_module.api.mailer"
            - "@zikula_groups_module.group_repository"
            - "@mu_posts_module.entity_display_helper"
            - "@mu_posts_module.workflow_helper"
    
    mu_posts_module.search_helper:
        class: MU\PostsModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@session"
            - "@request_stack"
            - "@mu_posts_module.entity_factory"
            - "@mu_posts_module.controller_helper"
            - "@mu_posts_module.entity_display_helper"
            - "@mu_posts_module.feature_activation_helper"
            - "@mu_posts_module.category_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: MUPostsModule }
    
    mu_posts_module.view_helper:
        class: MU\PostsModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@mu_posts_module.controller_helper"
    
    mu_posts_module.workflow_helper:
        class: MU\PostsModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@mu_posts_module.entity_factory"
            - "@mu_posts_module.listentries_helper"
