services:
    mu_posts_module.link_container:
        class: MU\PostsModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@mu_posts_module.controller_helper"
        tags: ['zikula.link_container']
