<?php
/**
 * Posts.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PostsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\PostsModule\Entity\ContentEntity;

/**
 * Event base class for filtering content processing.
 */
class AbstractFilterContentEvent extends Event
{
    /**
     * @var ContentEntity Reference to treated entity instance.
     */
    protected $content;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterContentEvent constructor.
     *
     * @param ContentEntity $content Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(ContentEntity $content, array $entityChangeSet = [])
    {
        $this->content = $content;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return ContentEntity
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
